name: golangci

on: push

jobs:
  lint:
    name: Linters
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: latest

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
        
    - name: Vet
      run: go vet ./...
      
    - name: Lint
      run: golint ./...
      
    - name: Test
      run: go test -v -race ./...
